name: Build JavaFX Runtime - Windows

on:
  workflow_dispatch:

jobs:
  build-windows-runtime:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Install Java 24
      - name: Setup Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      # Download JavaFX JMODs and SDK
      - name: Download JavaFX JMODs
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/24.0.2/openjfx-24.0.2_windows-x64_bin-jmods.zip -OutFile javafx-jmods.zip
          Expand-Archive javafx-jmods.zip -DestinationPath javafx-jmods

      - name: Download JavaFX SDK
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/24.0.2/openjfx-24.0.2_windows-x64_bin-sdk.zip -OutFile javafx-sdk.zip
          Expand-Archive javafx-sdk.zip -DestinationPath javafx-sdk

      # List all modules in javafx-jmods
      - name: Generate JavaFX module list
        shell: pwsh
        run: |
          $modules = Get-ChildItem javafx-jmods\*.jmod | ForEach-Object { $_.BaseName } 
          Write-Host "FX_MODULES=$($modules -join ',')" >> $env:GITHUB_ENV

      # Build runtime using jlink
      - name: Create custom JavaFX runtime
        shell: pwsh
        run: |
          $runtimeDir = "javafx-runtime"
          Remove-Item -Recurse -Force $runtimeDir -ErrorAction SilentlyContinue
          $modulePath = "javafx-jmods;$env:JAVA_HOME\jmods"
          jlink `
            --module-path $modulePath `
            --add-modules $env:FX_MODULES `
            --output $runtimeDir `
            --compress 2 `
            --strip-debug `
            --no-header-files `
            --no-man-pages

      # Copy SDK /lib for completeness
      - name: Copy JavaFX SDK /lib
        run: |
          Copy-Item -Path "javafx-sdk\lib\*" -Destination "javafx-runtime\lib" -Recurse -Force

      # Package runtime as zip
      - name: Package runtime
        run: |
          Compress-Archive -Path "javafx-runtime\*" -DestinationPath "javafx-runtime-windows.zip"

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: javafx-runtime-windows
          path: javafx-runtime-windows.zip
