name: Build JavaFX Runtime - Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-runtime:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Download JavaFX SDK and JMods
        run: |
          Invoke-WebRequest -Uri "https://download2.gluonhq.com/openjfx/24.0.2/openjfx-24.0.2_windows-x64_bin-sdk.zip" -OutFile "javafx-sdk.zip"
          Expand-Archive -Path "javafx-sdk.zip" -DestinationPath "javafx-sdk-24.0.2"

          Invoke-WebRequest -Uri "https://download2.gluonhq.com/openjfx/24.0.2/openjfx-24.0.2_windows-x64_bin-jmods.zip" -OutFile "javafx-jmods.zip"
          Expand-Archive -Path "javafx-jmods.zip" -DestinationPath "javafx-jmods"

      - name: Prepare JavaFX modules
        run: |
          # Create a comma-separated list of all module names
          $FX_MODULES = (Get-ChildItem javafx-jmods | ForEach-Object { $_.BaseName }) -join ","
          echo "FX_MODULES=$FX_MODULES" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Build JavaFX runtime
        run: |
          $modulePath = "$env:JAVA_HOME\jmods;javafx-jmods"
          $output = "javafx-runtime-24-windows"
          $fxModules = $env:FX_MODULES
          & "$env:JAVA_HOME\bin\jlink.exe" `
            --module-path $modulePath `
            --add-modules $fxModules `
            --output $output `
            --compress 2 `
            --strip-debug `
            --no-header-files `
            --no-man-pages

      - name: Zip JavaFX runtime
        run: |
          Compress-Archive -Path "javafx-runtime-24-windows" -DestinationPath "javafx-runtime-24-windows.zip"

      - name: Upload Windows runtime artifact
        uses: actions/upload-artifact@v4
        with:
          name: javafx-runtime-windows
          path: javafx-runtime-24-windows.zip
