name: Build JavaFX Runtimes (Linux, Windows, macOS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build JavaFX Runtime
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Download JavaFX SDK & JMODs
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            FX_OS="windows-x64"
          elif [ "$RUNNER_OS" = "macOS" ]; then
            FX_OS="osx-x64"
          else
            FX_OS="linux-x64"
          fi

          echo "Downloading JavaFX for $FX_OS..."
          curl -L -o openjfx-sdk.zip https://download2.gluonhq.com/openjfx/24.0.2/openjfx-24.0.2_${FX_OS}_bin-sdk.zip
          curl -L -o openjfx-jmods.zip https://download2.gluonhq.com/openjfx/24.0.2/openjfx-24.0.2_${FX_OS}_bin-jmods.zip

          unzip -q openjfx-sdk.zip -d javafx-sdk
          mkdir javafx-jmods
          unzip -q openjfx-jmods.zip -d javafx-jmods

      - name: Build runtime with jlink
        shell: bash
        run: |
          # List all javafx modules (basename removes .jmod extension)
          FX_MODULES=$(find javafx-jmods -name "*.jmod" -exec basename {} .jmod \; | paste -sd, -)

          echo "Found JavaFX modules: $FX_MODULES"

          $JAVA_HOME/bin/jlink \
            --module-path $JAVA_HOME/jmods:javafx-jmods \
            --add-modules $FX_MODULES \
            --output javafx-runtime-24-${{ matrix.os }} \
            --strip-debug \
            --compress=2 \
            --no-header-files \
            --no-man-pages

      - name: Zip runtime
        shell: bash
        run: zip -r javafx-runtime-24-${{ matrix.os }}.zip javafx-runtime-24-${{ matrix.os }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: javafx-runtime-24-${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
